# Generated by Django 3.2.9 on 2022-02-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.SmallIntegerField()),
                ('city', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=35)),
                ('team2', models.CharField(max_length=35)),
                ('toss_winner', models.CharField(max_length=35)),
                ('toss_decision', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=10)),
                ('dl_applied', models.BooleanField(default=0)),
                ('winner', models.CharField(max_length=35)),
                ('win_by_runs', models.SmallIntegerField()),
                ('win_by_wickets', models.SmallIntegerField()),
                ('player_of_match', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('umpire1', models.CharField(max_length=35)),
                ('umpire2', models.CharField(max_length=35)),
                ('umpire3', models.CharField(max_length=35)),
            ],
            options={
                'ordering': ('season',),
            },
        ),
        migrations.CreateModel(
            name='deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.SmallIntegerField()),
                ('batting_team', models.CharField(max_length=35)),
                ('bowling_team', models.CharField(max_length=35)),
                ('over', models.SmallIntegerField()),
                ('ball', models.SmallIntegerField()),
                ('batsman', models.CharField(max_length=35)),
                ('non_striker', models.CharField(max_length=35)),
                ('bowler', models.CharField(max_length=35)),
                ('is_super_over', models.BooleanField(default=0)),
                ('wide_runs', models.SmallIntegerField(default=0)),
                ('bye_runs', models.SmallIntegerField(default=0)),
                ('legbye_runs', models.SmallIntegerField(default=0)),
                ('noball_runs', models.SmallIntegerField(default=0)),
                ('penalty_runs', models.SmallIntegerField(default=0)),
                ('batsman_runs', models.SmallIntegerField(default=0)),
                ('extra_runs', models.SmallIntegerField(default=0)),
                ('total_runs', models.SmallIntegerField(default=0)),
                ('player_dismissed', models.CharField(max_length=35)),
                ('dismissal_kind', models.CharField(max_length=35)),
                ('fielder', models.CharField(max_length=35)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.matches')),
            ],
        ),
    ]
